// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaySpace_API.Models;

#nullable disable

namespace PaySpace_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231114070323_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaySpace_API.Models.FlatRateTaxRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("Id");

                    b.ToTable("FlatRateTaxRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TaxRate = 0.175m
                        });
                });

            modelBuilder.Entity("PaySpace_API.Models.FlatValueTaxRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FlatTaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncomeThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRateBelowThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FlatValueTaxRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlatTaxAmount = 10000m,
                            IncomeThreshold = 200000m,
                            TaxRateBelowThreshold = 0.05m
                        });
                });

            modelBuilder.Entity("PaySpace_API.Models.PostalCodeTaxType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalculationType")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PostalCodeTaxTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalculationType = 0,
                            PostalCode = "7441"
                        },
                        new
                        {
                            Id = 2,
                            CalculationType = 1,
                            PostalCode = "A100"
                        },
                        new
                        {
                            Id = 3,
                            CalculationType = 2,
                            PostalCode = "7000"
                        },
                        new
                        {
                            Id = 4,
                            CalculationType = 0,
                            PostalCode = "1000"
                        });
                });

            modelBuilder.Entity("PaySpace_API.Models.TaxCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CalculatedTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CalculationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaxCalculations");
                });

            modelBuilder.Entity("PaySpace_API.Models.TaxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FromIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ToIncome")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TaxRates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FromIncome = 0m,
                            Rate = 0.10m,
                            ToIncome = 8350m
                        },
                        new
                        {
                            Id = 2,
                            FromIncome = 8351m,
                            Rate = 0.15m,
                            ToIncome = 33950m
                        },
                        new
                        {
                            Id = 3,
                            FromIncome = 33951m,
                            Rate = 0.25m,
                            ToIncome = 82250m
                        },
                        new
                        {
                            Id = 4,
                            FromIncome = 82251m,
                            Rate = 0.28m,
                            ToIncome = 171550m
                        },
                        new
                        {
                            Id = 5,
                            FromIncome = 171551m,
                            Rate = 0.33m,
                            ToIncome = 372950m
                        },
                        new
                        {
                            Id = 6,
                            FromIncome = 372951m,
                            Rate = 0.35m,
                            ToIncome = 100000000m
                        });
                });

            modelBuilder.Entity("PaySpace_API.Models.UserIncomeDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserIncomeDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
